---
- name: data types
  hosts: frontend
  gather_facts: false

  tasks:
    - name: this is a value
      vars:
        course: "devops"
        hours: 150
        tags:
          - linux
          - windows
          - os
          - redhat
          - centos
        tags_map:
          name: "vinay"
          age: 26
          learning: "daily"

      ansible.builtin.debug:
        msg: "printing the value {{ tags[0] }} and {{ tags_map.learning }}"