---
- name: data types
  hosts: frontend

  tasks:
    - name: this is a value
      vars:
        course: "devops"
        hours: 150
        tas:
          - linux
          - windows
          - os
          - redhat
          - centos
        tas_map:
          name: "vinay"
          age: 26
          learning: "daily"

      ansible.builtin.debug:
        msg: "printing the value {{ tas[0] }} and {{ tas_map.learning }}"